#!/bin/bash -x
echo "Doorbell rung at: " `date` >> $HOME/iot_doorbell/knock-count
librespot=$(pacmd list-sink-inputs | tr '\n' '\r' | perl -pe 's/ *index: ([0-9]+).+?application\.process\.binary = "([^\r]+)"\r.+?(?=index:|$)/\2 : \1\r/g' | tr '\r' '\n' | awk '/librespot/{print $3}')

volume=75
pactl set-sink-input-volume $librespot -${volume}%
play /home/pi/iot_doorbell/ding.mp3
pactl set-sink-input-volume $librespot +${volume}%
